/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/test": {
    /**
     * Test endpoint
     * @description Returns a test message with user information
     */
    get: operations["gettest"];
  };
  "/games": {
    /**
     * Get all games
     * @description Retrieves all games with pagination support
     */
    get: operations["getgames"];
    /**
     * Create a new game
     * @description Creates a new game with the authenticated user as player1
     */
    post: operations["postgames"];
  };
  "/games/{gameId}/join": {
    /**
     * Join a game
     * @description Joins an existing game as player2
     */
    post: operations["postgamesJoin"];
  };
  "/games/{gameId}": {
    /**
     * Get a specific game
     * @description Retrieves details for a specific game by ID
     */
    get: operations["getgames"];
  };
  "/games/players/{playerId}": {
    /**
     * Get games for a player
     * @description Retrieves all games where the specified player is either player1 or player2
     */
    get: operations["getgamesPlayers"];
  };
  "/games/player1/{player1Id}": {
    /**
     * Get games created by player
     * @description Retrieves all games where the specified player is player1 (games they created)
     */
    get: operations["getgamesPlayer1"];
  };
  "/games/player2/{player2Id}": {
    /**
     * Get games joined by player
     * @description Retrieves all games where the specified player is player2 (games they joined)
     */
    get: operations["getgamesPlayer2"];
  };
  "/docs": {
    /**
     * API documentation
     * @description Interactive API documentation (Swagger UI)
     */
    get: operations["getdocs"];
  };
  "/docs/openapi.yaml": {
    /**
     * OpenAPI specification
     * @description OpenAPI 3.0 specification in YAML format
     */
    get: operations["getdocsOpenapi.yaml"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Player: {
      /** @description Player's display name */
      name: string;
      /** @description Cognito user ID (sub) - unique, immutable identifier */
      userId: string;
    };
    Game: {
      /**
       * Format: uuid
       * @description Unique game identifier
       */
      gameId: string;
      /**
       * @description Current game status
       * @enum {string}
       */
      status: "waiting" | "active" | "finished";
      player1: components["schemas"]["Player"];
      player2?: components["schemas"]["Player"];
      /** @description Index field - equals player1.userId */
      player1Id: string;
      /** @description Index field - equals player2.userId when player2 exists */
      player2Id?: string;
      /** @description Current turn number */
      turnNumber: number;
      /**
       * Format: date-time
       * @description Game creation timestamp
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Game last update timestamp
       */
      updatedAt?: string;
    };
    User: {
      /** @description Cognito user ID */
      userId?: string;
      /** @description Username */
      username?: string;
      /**
       * Format: email
       * @description User email
       */
      email?: string;
    };
    ErrorResponse: {
      /** @description Error message */
      error?: string;
      user?: components["schemas"]["User"];
      /** @description Additional error details */
      details?: string;
    };
    GameResponse: {
      /** Format: uuid */
      gameId?: string;
      game?: components["schemas"]["Game"];
      user?: components["schemas"]["User"];
    };
    JoinGameResponse: components["schemas"]["GameResponse"] & {
      /** @example Game is now active! */
      message?: string;
    };
    GamesResponse: {
      games?: components["schemas"]["Game"][];
      /** @description Number of games in this response */
      count?: number;
      /** @description Whether there are more games available */
      hasMore?: boolean;
      /** @description Token to fetch the next page of results */
      nextToken?: string;
      /** @description Filter parameter used (when querying by player) */
      playerId?: string;
      /** @description Filter parameter used (when querying by player1) */
      player1Id?: string;
      /** @description Filter parameter used (when querying by player2) */
      player2Id?: string;
      user?: components["schemas"]["User"];
    };
  };
  responses: {
    /** @description Bad request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Authentication required */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Resource not found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Internal server error */
    ServerError: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Test endpoint
   * @description Returns a test message with user information
   */
  gettest: {
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            user?: components["schemas"]["User"];
          };
        };
      };
      500: components["responses"]["ServerError"];
    };
  };
  /**
   * Get a specific game
   * @description Retrieves details for a specific game by ID
   */
  getgames: {
    parameters: {
      path: {
        /** @description Unique identifier for the game */
        gameId: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["GameResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["ServerError"];
    };
  };
  /**
   * Create a new game
   * @description Creates a new game with the authenticated user as player1
   */
  postgames: {
    parameters: {
      query?: {
        /** @description Maximum number of games to return (1-100) */
        limit?: number;
        /** @description Token for pagination (returned from previous request) */
        nextToken?: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** @description Optional player name (defaults to username or email) */
          playerName?: string;
        };
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["GameResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["ServerError"];
    };
  };
  /**
   * Join a game
   * @description Joins an existing game as player2
   */
  postgamesJoin: {
    parameters: {
      path: {
        /** @description Unique identifier for the game */
        gameId: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** @description Optional player name (defaults to username or email) */
          playerName?: string;
        };
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["JoinGameResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["ServerError"];
    };
  };
  /**
   * Get games for a player
   * @description Retrieves all games where the specified player is either player1 or player2
   */
  getgamesPlayers: {
    parameters: {
      query?: {
        /** @description Maximum number of games to return (1-100) */
        limit?: number;
        /** @description Token for pagination (returned from previous request) */
        nextToken?: string;
      };
      path: {
        /** @description User ID (Cognito sub) of the player */
        playerId: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["GamesResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["ServerError"];
    };
  };
  /**
   * Get games created by player
   * @description Retrieves all games where the specified player is player1 (games they created)
   */
  getgamesPlayer1: {
    parameters: {
      query?: {
        /** @description Maximum number of games to return (1-100) */
        limit?: number;
        /** @description Token for pagination (returned from previous request) */
        nextToken?: string;
      };
      path: {
        /** @description User ID (Cognito sub) of player1 */
        player1Id: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["GamesResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["ServerError"];
    };
  };
  /**
   * Get games joined by player
   * @description Retrieves all games where the specified player is player2 (games they joined)
   */
  getgamesPlayer2: {
    parameters: {
      query?: {
        /** @description Maximum number of games to return (1-100) */
        limit?: number;
        /** @description Token for pagination (returned from previous request) */
        nextToken?: string;
      };
      path: {
        /** @description User ID (Cognito sub) of player2 */
        player2Id: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["GamesResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["ServerError"];
    };
  };
  /**
   * API documentation
   * @description Interactive API documentation (Swagger UI)
   */
  getdocs: {
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "text/html": string;
        };
      };
    };
  };
  /**
   * OpenAPI specification
   * @description OpenAPI 3.0 specification in YAML format
   */
  "getdocsOpenapi.yaml": {
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "text/yaml": string;
        };
      };
    };
  };
}
